config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homepage#index"
  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    build_song
  end

  def create
    build_song
    save_song or render 'new'
  end

  def index
    load_songs
  end

  private
  def build_song
    @song ||= song_scope.build
    @song.attributes = song_params
  end

  def save_song
    if @song.save
      redirect_to songs_path
    end
  end

  def load_songs
    @songs ||= song_scope
  end

  def song_scope
    Song.all
  end

  def song_params
    song_params = params[:song]
    song_params ? song_params.permit(:title, :artist): {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item">Accueil</a>
    <a class="item">A propos</a>
    <div class="right menu">
      <div class="item">
        <a class="ui button">S'identifier</a>
      </div>
    </div>
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <a class="active item">Accueil</a>
  <a class="item">A propos</a>
  <a class="item">S'identifier</a>
</div>


<!-- Page Contents -->
<div class="pusher">
  <div class="ui vertical masthead center aligned inverted segment">

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <a class="active item">Accueil</a>
        <a class="item">A propos</a>
        <div class="right item">
          <a class="ui inverted button">S'identifier</a>
        </div>
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header">
        Préparez votre soirée Kismar
      </h1>
      <h2>Proposez les chansons que vous adorez !</h2>
      <button class="ui huge primary button">Explorer le répertoire Kismar <i class="right arrow icon"></i></button>
    </div>

  </div>

  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="eight wide column">
          <h3 class="ui header">We Help Companies and Companions</h3>
          <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
          <h3 class="ui header">We Make Bananas That Can Dance</h3>
          <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
        </div>
        <div class="six wide right floated column">
          <img src="assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
        </div>
      </div>
      <div class="row">
        <div class="center aligned column">
          <a class="ui huge button">Check Them Out</a>
        </div>
      </div>
    </div>
  </div>


  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a>
      <h4 class="ui horizontal header divider">
        <a href="#">Case Studies</a>
      </h4>
      <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a>
    </div>
  </div>


  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Sitemap</a>
            <a href="#" class="item">Contact Us</a>
            <a href="#" class="item">Religious Ceremonies</a>
            <a href="#" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Services</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Banana Pre-Order</a>
            <a href="#" class="item">DNA FAQ</a>
            <a href="#" class="item">How To Access</a>
            <a href="#" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Footer Header</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kismar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/menu' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_menu.html.haml
#menu
  = link_to 'Accueil', root_path
  = link_to 'Ajouter une chanson', new_song_path

app/views/songs/index.html.haml
%table.ui.celled.table.repertoire
  %thead
    %tr
      %th Titre
      %th Artiste
  %tbody
  - @songs.each do |song|
    %tr.song
      %td.title= song.title
      %td.artist= song.artist

app/views/songs/new.html.haml
- if @song.errors
  .errors
    = @song.errors.full_messages
= form_for(@song, html: { class: 'ui form' }) do |form|
  .fields
    .two.field
      = form.label :title
      = form.text_field :title
    .two.field
      = form.label :artist
      = form.text_field :artist
  = form.submit 'Ajouter la chanson'